"""add analysis root and scoped deck schema

Revision ID: 5112a5aad7b6
Revises: 0001_initial
Create Date: 2026-09-19 18:45:31.831507
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "5112a5aad7b6"
down_revision: Union[str, None] = "0001_initial"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis_root",
        sa.Column(
            "id", sa.Integer(), nullable=False, comment="分析作用域内部自增主键。"
        ),
        sa.Column(
            "root_path", sa.Text(), nullable=False, comment="用户拖入的根目录显示路径。"
        ),
        sa.Column(
            "root_path_key",
            sa.Text(),
            nullable=False,
            comment="规范化后的根路径唯一键。",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="记录创建时间。",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="记录最后更新时间。",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("root_path_key", name="uq_analysis_root_root_path_key"),
        comment="一次用户拖入形成的根目录分析作用域。",
    )
    op.create_table(
        "subtitle_directory",
        sa.Column("id", sa.Integer(), nullable=False, comment="字幕目录内部自增主键。"),
        sa.Column(
            "analysis_root_id",
            sa.Integer(),
            nullable=False,
            comment="所属分析作用域 ID。",
        ),
        sa.Column(
            "parent_directory_id",
            sa.Integer(),
            nullable=True,
            comment="父目录 ID；根目录为空。",
        ),
        sa.Column(
            "segment_name", sa.Text(), nullable=False, comment="当前目录名称片段。"
        ),
        sa.Column(
            "relative_path_key",
            sa.Text(),
            nullable=False,
            comment="相对于分析根目录的规范化路径唯一键。",
        ),
        sa.Column(
            "sort_order",
            sa.Integer(),
            nullable=False,
            comment="同一父目录下的稳定排序值。",
        ),
        sa.Column(
            "is_root",
            sa.Integer(),
            nullable=False,
            comment="是否为分析根目录；1 表示根目录。",
        ),
        sa.CheckConstraint(
            "(parent_directory_id IS NULL AND is_root = 1) OR (parent_directory_id IS NOT NULL AND is_root = 0)",
            name="ck_subtitle_directory_root_parent",
        ),
        sa.CheckConstraint("is_root IN (0, 1)", name="ck_subtitle_directory_is_root"),
        sa.CheckConstraint("sort_order >= 0", name="ck_subtitle_directory_sort_order"),
        sa.ForeignKeyConstraint(
            ["analysis_root_id"], ["analysis_root.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["parent_directory_id", "analysis_root_id"],
            ["subtitle_directory.id", "subtitle_directory.analysis_root_id"],
            name="fk_subtitle_directory_parent_scope",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "analysis_root_id",
            "relative_path_key",
            name="uq_subtitle_directory_root_relative_path",
        ),
        sa.UniqueConstraint(
            "id", "analysis_root_id", name="uq_subtitle_directory_id_analysis_root"
        ),
        sa.UniqueConstraint("id", "is_root", name="uq_subtitle_directory_id_is_root"),
        comment="分析作用域内的本地字幕目录树节点。",
    )
    with op.batch_alter_table("subtitle_directory", schema=None) as batch_op:
        batch_op.create_index(
            "uq_subtitle_directory_sibling_order",
            ["parent_directory_id", "sort_order"],
            unique=True,
            sqlite_where=sa.text("parent_directory_id IS NOT NULL"),
        )
        batch_op.create_index(
            "uq_subtitle_directory_sibling_segment",
            ["parent_directory_id", "segment_name"],
            unique=True,
            sqlite_where=sa.text("parent_directory_id IS NOT NULL"),
        )
        batch_op.create_index(
            "uq_subtitle_directory_single_root",
            ["analysis_root_id"],
            unique=True,
            sqlite_where=sa.text("is_root = 1"),
        )

    op.create_table(
        "root_deck",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
            comment="Anki 根 deck 映射内部自增主键。",
        ),
        sa.Column(
            "root_directory_id",
            sa.Integer(),
            nullable=False,
            comment="对应的字幕根目录 ID。",
        ),
        sa.Column(
            "directory_is_root",
            sa.Integer(),
            nullable=False,
            comment="用于复合外键固定根目录类型；固定为 1。",
        ),
        sa.Column(
            "external_deck_id",
            sa.BigInteger(),
            nullable=True,
            comment="Anki 返回的远端 deck ID；尚未同步时为空。",
        ),
        sa.Column(
            "last_synced_at",
            sa.DateTime(),
            nullable=True,
            comment="最后一次同步成功时间。",
        ),
        sa.CheckConstraint(
            "directory_is_root = 1", name="ck_root_deck_directory_is_root"
        ),
        sa.ForeignKeyConstraint(
            ["root_directory_id", "directory_is_root"],
            ["subtitle_directory.id", "subtitle_directory.is_root"],
            name="fk_root_deck_root_directory",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_deck_id", name="uq_root_deck_external_deck"),
        sa.UniqueConstraint(
            "id", "directory_is_root", name="uq_root_deck_id_directory_is_root"
        ),
        sa.UniqueConstraint("root_directory_id", name="uq_root_deck_root_directory"),
        comment="分析根目录对应的 Anki 根 deck。",
    )
    op.create_table(
        "subtitle_file",
        sa.Column("id", sa.Integer(), nullable=False, comment="字幕文件内部自增主键。"),
        sa.Column(
            "directory_id", sa.Integer(), nullable=False, comment="所属字幕目录 ID。"
        ),
        sa.Column(
            "content_hash",
            sa.Text(),
            nullable=False,
            comment="字幕文件内容哈希，用于识别文件变化，不用于去重。",
        ),
        sa.Column("name", sa.Text(), nullable=False, comment="字幕文件名称。"),
        sa.Column(
            "path", sa.Text(), nullable=False, comment="字幕文件的规范化绝对路径。"
        ),
        sa.ForeignKeyConstraint(
            ["directory_id"], ["subtitle_directory.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "directory_id", "name", name="uq_subtitle_file_directory_name"
        ),
        sa.UniqueConstraint("path", name="uq_subtitle_file_path"),
        comment="字幕目录中的本地字幕文件。",
    )
    with op.batch_alter_table("subtitle_file", schema=None) as batch_op:
        batch_op.create_index("subtitle_file_directory", ["directory_id"], unique=False)

    op.create_table(
        "deck_node",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
            comment="Anki 普通 deck 映射内部自增主键。",
        ),
        sa.Column(
            "root_deck_id",
            sa.Integer(),
            nullable=False,
            comment="所属 Anki 根 deck ID。",
        ),
        sa.Column(
            "directory_id",
            sa.Integer(),
            nullable=False,
            comment="对应的非根字幕目录 ID。",
        ),
        sa.Column(
            "directory_is_root",
            sa.Integer(),
            nullable=False,
            comment="用于复合外键固定非根目录类型；固定为 0。",
        ),
        sa.Column(
            "parent_root_deck_id",
            sa.Integer(),
            nullable=True,
            comment="父节点为根 deck 时的 ID；否则为空。",
        ),
        sa.Column(
            "parent_deck_id",
            sa.Integer(),
            nullable=True,
            comment="父节点为普通 deck 时的 ID；否则为空。",
        ),
        sa.Column(
            "external_deck_id",
            sa.BigInteger(),
            nullable=True,
            comment="Anki 返回的远端 deck ID；尚未同步时为空。",
        ),
        sa.Column(
            "last_synced_at",
            sa.DateTime(),
            nullable=True,
            comment="最后一次同步成功时间。",
        ),
        sa.CheckConstraint(
            "(parent_root_deck_id IS NOT NULL AND parent_deck_id IS NULL) OR (parent_root_deck_id IS NULL AND parent_deck_id IS NOT NULL)",
            name="ck_deck_node_single_parent",
        ),
        sa.CheckConstraint(
            "directory_is_root = 0", name="ck_deck_node_directory_is_root"
        ),
        sa.CheckConstraint(
            "parent_root_deck_id IS NULL OR parent_root_deck_id = root_deck_id",
            name="ck_deck_node_parent_root_scope",
        ),
        sa.ForeignKeyConstraint(
            ["directory_id", "directory_is_root"],
            ["subtitle_directory.id", "subtitle_directory.is_root"],
            name="fk_deck_node_directory",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_deck_id", "root_deck_id"],
            ["deck_node.id", "deck_node.root_deck_id"],
            name="fk_deck_node_parent_deck",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["parent_root_deck_id"], ["root_deck.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["root_deck_id"], ["root_deck.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("directory_id", name="uq_deck_node_directory"),
        sa.UniqueConstraint("external_deck_id", name="uq_deck_node_external_deck"),
        sa.UniqueConstraint("id", "root_deck_id", name="uq_deck_node_id_root_deck"),
        comment="属于某个 Anki 根 deck 的普通 deck 节点。",
    )
    with op.batch_alter_table("deck_node", schema=None) as batch_op:
        batch_op.create_index("deck_node_parent_deck", ["parent_deck_id"], unique=False)
        batch_op.create_index(
            "deck_node_parent_root", ["parent_root_deck_id"], unique=False
        )

    op.create_table(
        "subtitle_entry",
        sa.Column("id", sa.Integer(), nullable=False, comment="字幕条目内部自增主键。"),
        sa.Column(
            "subtitle_file_id",
            sa.Integer(),
            nullable=False,
            comment="所属字幕文件 ID。",
        ),
        sa.Column(
            "number", sa.Integer(), nullable=False, comment="字幕文件中的条目编号。"
        ),
        sa.Column(
            "start_ms",
            sa.Integer(),
            nullable=False,
            comment="字幕开始时间，媒体相对毫秒。",
        ),
        sa.Column(
            "end_ms",
            sa.Integer(),
            nullable=False,
            comment="字幕结束时间，媒体相对毫秒。",
        ),
        sa.Column("text_ja", sa.Text(), nullable=False, comment="字幕中的日文文本。"),
        sa.Column(
            "text_zh_hans",
            sa.Text(),
            nullable=True,
            comment="字幕中的简体中文文本；没有翻译时为空。",
        ),
        sa.CheckConstraint("end_ms >= start_ms", name="ck_subtitle_entry_time_range"),
        sa.CheckConstraint("number >= 0", name="ck_subtitle_entry_number"),
        sa.CheckConstraint("start_ms >= 0", name="ck_subtitle_entry_start_ms"),
        sa.ForeignKeyConstraint(
            ["subtitle_file_id"], ["subtitle_file.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "subtitle_file_id", "number", name="uq_subtitle_entry_file_number"
        ),
        comment="字幕文件中的一条时间轴字幕。",
    )
    with op.batch_alter_table("subtitle_entry", schema=None) as batch_op:
        batch_op.create_index(
            "subtitle_entry_file", ["subtitle_file_id", "number"], unique=False
        )

    op.create_table(
        "anki_note",
        sa.Column(
            "id", sa.Integer(), nullable=False, comment="Anki note 映射内部自增主键。"
        ),
        sa.Column(
            "word_id", sa.Integer(), nullable=False, comment="对应的词典词条 ID。"
        ),
        sa.Column(
            "collection_root_deck_id",
            sa.Integer(),
            nullable=False,
            comment="作为 collection 根节点的 Anki 根 deck ID。",
        ),
        sa.Column(
            "home_deck_id",
            sa.Integer(),
            nullable=False,
            comment="note 当前归属的 Anki 普通 deck ID。",
        ),
        sa.Column(
            "external_note_id",
            sa.BigInteger(),
            nullable=True,
            comment="AnkiConnect 返回的远端 note ID；尚未同步时为空。",
        ),
        sa.Column(
            "anki_guid",
            sa.Text(),
            nullable=True,
            comment="Anki note 的真实 GUID；尚未取得时为空。",
        ),
        sa.Column(
            "external_card_id",
            sa.BigInteger(),
            nullable=True,
            comment="Anki 返回的远端 card ID；尚未同步时为空。",
        ),
        sa.Column(
            "last_synced_at",
            sa.DateTime(),
            nullable=True,
            comment="最后一次同步成功时间。",
        ),
        sa.ForeignKeyConstraint(
            ["collection_root_deck_id"], ["root_deck.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["home_deck_id", "collection_root_deck_id"],
            ["deck_node.id", "deck_node.root_deck_id"],
            name="fk_anki_note_home_deck_scope",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["word_id"], ["word.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("anki_guid", name="uq_anki_note_anki_guid"),
        sa.UniqueConstraint("external_card_id", name="uq_anki_note_external_card"),
        sa.UniqueConstraint("external_note_id", name="uq_anki_note_external_note"),
        sa.UniqueConstraint(
            "word_id",
            "collection_root_deck_id",
            name="uq_anki_note_word_collection_root_deck",
        ),
        comment="词典词条在某个根 deck 范围内的稳定 note 映射。",
    )
    with op.batch_alter_table("anki_note", schema=None) as batch_op:
        batch_op.create_index(
            "anki_note_collection_root_deck", ["collection_root_deck_id"], unique=False
        )
        batch_op.create_index("anki_note_home_deck", ["home_deck_id"], unique=False)
        batch_op.create_index("anki_note_word", ["word_id"], unique=False)

    op.create_table(
        "word_occurrence",
        sa.Column("id", sa.Integer(), nullable=False, comment="词项出现内部自增主键。"),
        sa.Column(
            "entry_id", sa.Integer(), nullable=False, comment="所属字幕条目 ID。"
        ),
        sa.Column(
            "word_form_id",
            sa.Integer(),
            nullable=False,
            comment="匹配到的词典词形 ID。",
        ),
        sa.Column(
            "matched_text",
            sa.Text(),
            nullable=False,
            comment="在字幕日文文本中命中的实际文本。",
        ),
        sa.Column(
            "position",
            sa.Integer(),
            nullable=False,
            comment="同一个字幕条目内的出现位置标识。",
        ),
        sa.CheckConstraint("position >= 0", name="ck_word_occurrence_position"),
        sa.ForeignKeyConstraint(
            ["entry_id"], ["subtitle_entry.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["word_form_id"], ["word_form.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "entry_id",
            "word_form_id",
            "position",
            name="uq_word_occurrence_entry_form_position",
        ),
        comment="字幕条目中已解析到词典词形的词项出现。",
    )
    with op.batch_alter_table("word_occurrence", schema=None) as batch_op:
        batch_op.create_index("word_occurrence_entry", ["entry_id"], unique=False)
        batch_op.create_index("word_occurrence_form", ["word_form_id"], unique=False)

    op.create_table(
        "anki_note_occurrence",
        sa.Column(
            "id", sa.Integer(), nullable=False, comment="note 词项关联内部自增主键。"
        ),
        sa.Column(
            "anki_note_id",
            sa.Integer(),
            nullable=False,
            comment="所属 Anki note 映射 ID。",
        ),
        sa.Column(
            "occurrence_id",
            sa.Integer(),
            nullable=False,
            comment="已追加到该 note 的字幕词项出现 ID。",
        ),
        sa.ForeignKeyConstraint(["anki_note_id"], ["anki_note.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["occurrence_id"], ["word_occurrence.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "anki_note_id",
            "occurrence_id",
            name="uq_anki_note_occurrence_note_occurrence",
        ),
        comment="Anki note 已引用的字幕词项出现证据。",
    )
    with op.batch_alter_table("anki_note_occurrence", schema=None) as batch_op:
        batch_op.create_index(
            "anki_note_occurrence_note", ["anki_note_id"], unique=False
        )
        batch_op.create_index(
            "anki_note_occurrence_occurrence", ["occurrence_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("anki_note_occurrence", schema=None) as batch_op:
        batch_op.drop_index("anki_note_occurrence_occurrence")
        batch_op.drop_index("anki_note_occurrence_note")

    op.drop_table("anki_note_occurrence")
    with op.batch_alter_table("word_occurrence", schema=None) as batch_op:
        batch_op.drop_index("word_occurrence_form")
        batch_op.drop_index("word_occurrence_entry")

    op.drop_table("word_occurrence")
    with op.batch_alter_table("anki_note", schema=None) as batch_op:
        batch_op.drop_index("anki_note_word")
        batch_op.drop_index("anki_note_home_deck")
        batch_op.drop_index("anki_note_collection_root_deck")

    op.drop_table("anki_note")
    with op.batch_alter_table("subtitle_entry", schema=None) as batch_op:
        batch_op.drop_index("subtitle_entry_file")

    op.drop_table("subtitle_entry")
    with op.batch_alter_table("deck_node", schema=None) as batch_op:
        batch_op.drop_index("deck_node_parent_root")
        batch_op.drop_index("deck_node_parent_deck")

    op.drop_table("deck_node")
    with op.batch_alter_table("subtitle_file", schema=None) as batch_op:
        batch_op.drop_index("subtitle_file_directory")

    op.drop_table("subtitle_file")
    op.drop_table("root_deck")
    with op.batch_alter_table("subtitle_directory", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_subtitle_directory_single_root", sqlite_where=sa.text("is_root = 1")
        )
        batch_op.drop_index(
            "uq_subtitle_directory_sibling_segment",
            sqlite_where=sa.text("parent_directory_id IS NOT NULL"),
        )
        batch_op.drop_index(
            "uq_subtitle_directory_sibling_order",
            sqlite_where=sa.text("parent_directory_id IS NOT NULL"),
        )

    op.drop_table("subtitle_directory")
    op.drop_table("analysis_root")
    # ### end Alembic commands ###
