"""add analysis request and normalized learning schema

Revision ID: 8a15dc441d27
Revises: 0001_initial
Create Date: 2026-09-23 02:17:04.252795
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "8a15dc441d27"
down_revision: Union[str, None] = "0001_initial"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis_request",
        sa.Column("id", sa.Integer(), nullable=False, comment="分析请求内部自增主键。"),
        sa.Column(
            "requested_path",
            sa.Text(),
            nullable=False,
            comment="用户请求分析的显示路径。",
        ),
        sa.Column(
            "requested_path_key",
            sa.Text(),
            nullable=False,
            comment="规范化后的请求路径。",
        ),
        sa.Column(
            "started_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="请求创建时间。",
        ),
        sa.Column("status", sa.Text(), nullable=False, comment="请求当前状态。"),
        sa.Column(
            "model_name", sa.Text(), nullable=True, comment="本次请求使用的模型名称。"
        ),
        sa.Column(
            "prompt_version",
            sa.Text(),
            nullable=True,
            comment="本次请求使用的提示词版本。",
        ),
        sa.Column(
            "options_json", sa.JSON(), nullable=False, comment="本次请求的参数快照。"
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="一次用户提交的字幕分析请求。",
    )
    op.create_table(
        "deck",
        sa.Column(
            "id", sa.Integer(), nullable=False, comment="Anki deck 映射内部自增主键。"
        ),
        sa.Column(
            "deck_kind",
            sa.Text(),
            nullable=False,
            comment="deck 类型，root 或 normal。",
        ),
        sa.Column(
            "parent_deck_id",
            sa.Integer(),
            nullable=True,
            comment="父 deck ID；根 deck 为空。",
        ),
        sa.Column(
            "root_deck_id",
            sa.Integer(),
            nullable=False,
            comment="所属根 deck ID；根 deck 指向自身。",
        ),
        sa.Column(
            "relative_deck_path",
            sa.Text(),
            nullable=False,
            comment="相对于根 deck 的规范路径。",
        ),
        sa.Column(
            "external_deck_id",
            sa.BigInteger(),
            nullable=True,
            comment="Anki 返回的远端 deck ID；尚未同步时为空。",
        ),
        sa.Column(
            "last_synced_at",
            sa.DateTime(),
            nullable=True,
            comment="最后一次同步成功时间。",
        ),
        sa.CheckConstraint(
            "(deck_kind = 'root' AND parent_deck_id IS NULL AND root_deck_id = id) OR (deck_kind = 'normal' AND parent_deck_id IS NOT NULL AND root_deck_id <> id)",
            name="ck_deck_kind_parent_scope",
        ),
        sa.CheckConstraint("deck_kind IN ('root', 'normal')", name="ck_deck_kind"),
        sa.ForeignKeyConstraint(
            ["parent_deck_id", "root_deck_id"],
            ["deck.id", "deck.root_deck_id"],
            name="fk_deck_parent_scope",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["root_deck_id"], ["deck.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_deck_id", name="uq_deck_external_deck"),
        sa.UniqueConstraint("id", "root_deck_id", name="uq_deck_id_root_deck"),
        sa.UniqueConstraint(
            "root_deck_id", "relative_deck_path", name="uq_deck_root_relative_path"
        ),
        comment="Anki deck 树中的通用根 deck 和普通 deck 节点。",
    )
    with op.batch_alter_table("deck", schema=None) as batch_op:
        batch_op.create_index("deck_parent", ["parent_deck_id"], unique=False)

    op.create_table(
        "subtitle_directory",
        sa.Column("id", sa.Integer(), nullable=False, comment="字幕目录内部自增主键。"),
        sa.Column("path", sa.Text(), nullable=False, comment="目录的规范化绝对路径。"),
        sa.Column(
            "path_key", sa.Text(), nullable=False, comment="目录规范化路径唯一键。"
        ),
        sa.Column(
            "parent_directory_id",
            sa.Integer(),
            nullable=True,
            comment="父目录 ID；根目录为空。",
        ),
        sa.Column(
            "segment_name", sa.Text(), nullable=False, comment="当前目录名称片段。"
        ),
        sa.Column(
            "sort_order",
            sa.Integer(),
            nullable=False,
            comment="同一父目录下的稳定排序值。",
        ),
        sa.CheckConstraint("sort_order >= 0", name="ck_subtitle_directory_sort_order"),
        sa.ForeignKeyConstraint(
            ["parent_directory_id"], ["subtitle_directory.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("path_key", name="uq_subtitle_directory_path_key"),
        comment="本地字幕目录树的邻接表节点。",
    )
    with op.batch_alter_table("subtitle_directory", schema=None) as batch_op:
        batch_op.create_index(
            "uq_subtitle_directory_root_order",
            ["sort_order"],
            unique=True,
            sqlite_where=sa.text("parent_directory_id IS NULL"),
        )
        batch_op.create_index(
            "uq_subtitle_directory_root_segment",
            ["segment_name"],
            unique=True,
            sqlite_where=sa.text("parent_directory_id IS NULL"),
        )
        batch_op.create_index(
            "uq_subtitle_directory_sibling_order",
            ["parent_directory_id", "sort_order"],
            unique=True,
            sqlite_where=sa.text("parent_directory_id IS NOT NULL"),
        )
        batch_op.create_index(
            "uq_subtitle_directory_sibling_segment",
            ["parent_directory_id", "segment_name"],
            unique=True,
            sqlite_where=sa.text("parent_directory_id IS NOT NULL"),
        )

    op.create_table(
        "analyzes",
        sa.Column(
            "analysis_request_id",
            sa.Integer(),
            nullable=False,
            comment="所属分析请求 ID。",
        ),
        sa.Column(
            "directory_id", sa.Integer(), nullable=False, comment="被分析的目录 ID。"
        ),
        sa.Column(
            "is_root",
            sa.Integer(),
            nullable=False,
            comment="是否为该请求的根目录；1 表示根目录。",
        ),
        sa.Column("depth", sa.Integer(), nullable=False, comment="相对根目录的深度。"),
        sa.CheckConstraint(
            "(is_root = 1 AND depth = 0) OR (is_root = 0 AND depth > 0)",
            name="ck_analyzes_root_depth",
        ),
        sa.CheckConstraint("depth >= 0", name="ck_analyzes_depth"),
        sa.CheckConstraint("is_root IN (0, 1)", name="ck_analyzes_is_root"),
        sa.ForeignKeyConstraint(
            ["analysis_request_id"], ["analysis_request.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["directory_id"], ["subtitle_directory.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("analysis_request_id", "directory_id"),
        comment="分析请求与其覆盖目录之间的分析联系。",
    )
    with op.batch_alter_table("analyzes", schema=None) as batch_op:
        batch_op.create_index("analyzes_directory", ["directory_id"], unique=False)
        batch_op.create_index(
            "uq_analyzes_single_root",
            ["analysis_request_id"],
            unique=True,
            sqlite_where=sa.text("is_root = 1"),
        )

    op.create_table(
        "normal_deck",
        sa.Column(
            "deck_id", sa.Integer(), nullable=False, comment="对应的通用 deck ID。"
        ),
        sa.Column(
            "directory_id", sa.Integer(), nullable=False, comment="对应的字幕目录 ID。"
        ),
        sa.ForeignKeyConstraint(["deck_id"], ["deck.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["directory_id"], ["subtitle_directory.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("deck_id"),
        sa.UniqueConstraint("directory_id", name="uq_normal_deck_directory"),
        comment="映射非根字幕目录的 Anki 普通 deck 特化。",
    )
    op.create_table(
        "root_deck",
        sa.Column(
            "deck_id", sa.Integer(), nullable=False, comment="对应的通用 deck ID。"
        ),
        sa.Column(
            "root_directory_id",
            sa.Integer(),
            nullable=False,
            comment="对应的字幕目录 ID。",
        ),
        sa.ForeignKeyConstraint(["deck_id"], ["deck.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["root_directory_id"], ["subtitle_directory.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("deck_id"),
        sa.UniqueConstraint("root_directory_id", name="uq_root_deck_root_directory"),
        comment="映射分析根目录的 Anki 根 deck 特化。",
    )
    op.create_table(
        "subtitle_file",
        sa.Column("id", sa.Integer(), nullable=False, comment="字幕文件内部自增主键。"),
        sa.Column(
            "directory_id", sa.Integer(), nullable=False, comment="所属字幕目录 ID。"
        ),
        sa.Column(
            "content_hash",
            sa.Text(),
            nullable=False,
            comment="字幕文件内容哈希，用于识别文件变化，不用于去重。",
        ),
        sa.Column("name", sa.Text(), nullable=False, comment="字幕文件名称。"),
        sa.Column(
            "path", sa.Text(), nullable=False, comment="字幕文件的规范化绝对路径。"
        ),
        sa.ForeignKeyConstraint(
            ["directory_id"], ["subtitle_directory.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "directory_id", "name", name="uq_subtitle_file_directory_name"
        ),
        sa.UniqueConstraint("path", name="uq_subtitle_file_path"),
        comment="字幕目录中的本地字幕文件。",
    )
    with op.batch_alter_table("subtitle_file", schema=None) as batch_op:
        batch_op.create_index("subtitle_file_directory", ["directory_id"], unique=False)

    op.create_table(
        "anki_note",
        sa.Column(
            "id", sa.Integer(), nullable=False, comment="Anki note 映射内部自增主键。"
        ),
        sa.Column(
            "word_id", sa.Integer(), nullable=False, comment="对应的词典词条 ID。"
        ),
        sa.Column(
            "collection_root_deck_id",
            sa.Integer(),
            nullable=False,
            comment="作为 collection 根节点的 Anki 根 deck ID。",
        ),
        sa.Column(
            "home_deck_id",
            sa.Integer(),
            nullable=False,
            comment="note 当前归属的 Anki deck ID。",
        ),
        sa.Column(
            "external_note_id",
            sa.BigInteger(),
            nullable=True,
            comment="AnkiConnect 返回的远端 note ID；尚未同步时为空。",
        ),
        sa.Column(
            "anki_guid",
            sa.Text(),
            nullable=True,
            comment="Anki note 的真实 GUID；尚未取得时为空。",
        ),
        sa.Column(
            "external_card_id",
            sa.BigInteger(),
            nullable=True,
            comment="Anki 返回的远端 card ID；尚未同步时为空。",
        ),
        sa.Column(
            "last_synced_at",
            sa.DateTime(),
            nullable=True,
            comment="最后一次同步成功时间。",
        ),
        sa.ForeignKeyConstraint(
            ["collection_root_deck_id"], ["root_deck.deck_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["home_deck_id", "collection_root_deck_id"],
            ["deck.id", "deck.root_deck_id"],
            name="fk_anki_note_home_deck_scope",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["home_deck_id"], ["deck.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["word_id"], ["word.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("anki_guid", name="uq_anki_note_anki_guid"),
        sa.UniqueConstraint("external_card_id", name="uq_anki_note_external_card"),
        sa.UniqueConstraint("external_note_id", name="uq_anki_note_external_note"),
        sa.UniqueConstraint(
            "word_id",
            "collection_root_deck_id",
            name="uq_anki_note_word_collection_root_deck",
        ),
        comment="词典词条在某个根 deck 范围内的稳定 note 映射。",
    )
    with op.batch_alter_table("anki_note", schema=None) as batch_op:
        batch_op.create_index(
            "anki_note_collection_root_deck", ["collection_root_deck_id"], unique=False
        )
        batch_op.create_index("anki_note_home_deck", ["home_deck_id"], unique=False)
        batch_op.create_index("anki_note_word", ["word_id"], unique=False)

    op.create_table(
        "subtitle_entry",
        sa.Column("id", sa.Integer(), nullable=False, comment="字幕条目内部自增主键。"),
        sa.Column(
            "subtitle_file_id",
            sa.Integer(),
            nullable=False,
            comment="所属字幕文件 ID。",
        ),
        sa.Column(
            "number", sa.Integer(), nullable=False, comment="字幕文件中的条目编号。"
        ),
        sa.Column(
            "start_ms",
            sa.Integer(),
            nullable=False,
            comment="字幕开始时间，媒体相对毫秒。",
        ),
        sa.Column(
            "end_ms",
            sa.Integer(),
            nullable=False,
            comment="字幕结束时间，媒体相对毫秒。",
        ),
        sa.Column("text_ja", sa.Text(), nullable=False, comment="字幕中的日文文本。"),
        sa.Column(
            "text_zh_hans",
            sa.Text(),
            nullable=True,
            comment="字幕中的简体中文文本；没有翻译时为空。",
        ),
        sa.CheckConstraint("end_ms >= start_ms", name="ck_subtitle_entry_time_range"),
        sa.CheckConstraint("number >= 0", name="ck_subtitle_entry_number"),
        sa.CheckConstraint("start_ms >= 0", name="ck_subtitle_entry_start_ms"),
        sa.ForeignKeyConstraint(
            ["subtitle_file_id"], ["subtitle_file.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "subtitle_file_id", "number", name="uq_subtitle_entry_file_number"
        ),
        comment="字幕文件中的一条时间轴字幕。",
    )
    with op.batch_alter_table("subtitle_entry", schema=None) as batch_op:
        batch_op.create_index(
            "subtitle_entry_file", ["subtitle_file_id", "number"], unique=False
        )

    op.create_table(
        "word_occurrence",
        sa.Column("id", sa.Integer(), nullable=False, comment="词项出现内部自增主键。"),
        sa.Column(
            "entry_id", sa.Integer(), nullable=False, comment="所属字幕条目 ID。"
        ),
        sa.Column(
            "word_form_id",
            sa.Integer(),
            nullable=False,
            comment="匹配到的词典词形 ID。",
        ),
        sa.Column(
            "matched_text",
            sa.Text(),
            nullable=False,
            comment="在字幕日文文本中命中的实际文本。",
        ),
        sa.Column(
            "position",
            sa.Integer(),
            nullable=False,
            comment="同一个字幕条目内的出现位置标识。",
        ),
        sa.CheckConstraint("position >= 0", name="ck_word_occurrence_position"),
        sa.ForeignKeyConstraint(
            ["entry_id"], ["subtitle_entry.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["word_form_id"], ["word_form.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "entry_id",
            "word_form_id",
            "position",
            name="uq_word_occurrence_entry_form_position",
        ),
        comment="字幕条目中已解析到词典词形的词项出现。",
    )
    with op.batch_alter_table("word_occurrence", schema=None) as batch_op:
        batch_op.create_index("word_occurrence_entry", ["entry_id"], unique=False)
        batch_op.create_index("word_occurrence_form", ["word_form_id"], unique=False)

    op.create_table(
        "anki_note_occurrence",
        sa.Column(
            "id", sa.Integer(), nullable=False, comment="note 词项关联内部自增主键。"
        ),
        sa.Column(
            "anki_note_id",
            sa.Integer(),
            nullable=False,
            comment="所属 Anki note 映射 ID。",
        ),
        sa.Column(
            "occurrence_id",
            sa.Integer(),
            nullable=False,
            comment="已追加到该 note 的字幕词项出现 ID。",
        ),
        sa.ForeignKeyConstraint(["anki_note_id"], ["anki_note.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["occurrence_id"], ["word_occurrence.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "anki_note_id",
            "occurrence_id",
            name="uq_anki_note_occurrence_note_occurrence",
        ),
        comment="Anki note 已引用的字幕词项出现证据。",
    )
    with op.batch_alter_table("anki_note_occurrence", schema=None) as batch_op:
        batch_op.create_index(
            "anki_note_occurrence_note", ["anki_note_id"], unique=False
        )
        batch_op.create_index(
            "anki_note_occurrence_occurrence", ["occurrence_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("anki_note_occurrence", schema=None) as batch_op:
        batch_op.drop_index("anki_note_occurrence_occurrence")
        batch_op.drop_index("anki_note_occurrence_note")

    op.drop_table("anki_note_occurrence")
    with op.batch_alter_table("word_occurrence", schema=None) as batch_op:
        batch_op.drop_index("word_occurrence_form")
        batch_op.drop_index("word_occurrence_entry")

    op.drop_table("word_occurrence")
    with op.batch_alter_table("subtitle_entry", schema=None) as batch_op:
        batch_op.drop_index("subtitle_entry_file")

    op.drop_table("subtitle_entry")
    with op.batch_alter_table("anki_note", schema=None) as batch_op:
        batch_op.drop_index("anki_note_word")
        batch_op.drop_index("anki_note_home_deck")
        batch_op.drop_index("anki_note_collection_root_deck")

    op.drop_table("anki_note")
    with op.batch_alter_table("subtitle_file", schema=None) as batch_op:
        batch_op.drop_index("subtitle_file_directory")

    op.drop_table("subtitle_file")
    op.drop_table("root_deck")
    op.drop_table("normal_deck")
    with op.batch_alter_table("analyzes", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_analyzes_single_root", sqlite_where=sa.text("is_root = 1")
        )
        batch_op.drop_index("analyzes_directory")

    op.drop_table("analyzes")
    with op.batch_alter_table("subtitle_directory", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_subtitle_directory_sibling_segment",
            sqlite_where=sa.text("parent_directory_id IS NOT NULL"),
        )
        batch_op.drop_index(
            "uq_subtitle_directory_sibling_order",
            sqlite_where=sa.text("parent_directory_id IS NOT NULL"),
        )
        batch_op.drop_index(
            "uq_subtitle_directory_root_segment",
            sqlite_where=sa.text("parent_directory_id IS NULL"),
        )
        batch_op.drop_index(
            "uq_subtitle_directory_root_order",
            sqlite_where=sa.text("parent_directory_id IS NULL"),
        )

    op.drop_table("subtitle_directory")
    with op.batch_alter_table("deck", schema=None) as batch_op:
        batch_op.drop_index("deck_parent")

    op.drop_table("deck")
    op.drop_table("analysis_request")
    # ### end Alembic commands ###
