"""Add subtitle, occurrence, and Anki mapping schema.

Revision ID: 9678b76a34a5
Revises: 0001_initial
Create Date: 2026-09-19 17:51:51.850928
"""

from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "9678b76a34a5"
down_revision: str | None = "0001_initial"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subtitle_collection",
        sa.Column("id", sa.Integer(), nullable=False, comment="字幕集合内部自增主键。"),
        sa.Column(
            "path", sa.Text(), nullable=False, comment="字幕集合的规范化绝对路径。"
        ),
        sa.Column("name", sa.Text(), nullable=False, comment="字幕集合显示名称。"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("path", name="uq_subtitle_collection_path"),
        comment="本地字幕目录组成的字幕集合。",
    )
    op.create_table(
        "anki_deck_collection",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
            comment="Anki 集合级 deck 映射内部自增主键。",
        ),
        sa.Column(
            "subtitle_collection_id",
            sa.Integer(),
            nullable=False,
            comment="对应的字幕集合 ID。",
        ),
        sa.Column(
            "external_deck_id",
            sa.BigInteger(),
            nullable=True,
            comment="Anki 返回的远端 deck ID；尚未同步时为空。",
        ),
        sa.Column(
            "deck_name", sa.Text(), nullable=False, comment="Anki deck 完整名称。"
        ),
        sa.Column(
            "last_synced_at",
            sa.DateTime(),
            nullable=True,
            comment="最后一次同步成功时间。",
        ),
        sa.ForeignKeyConstraint(
            ["subtitle_collection_id"], ["subtitle_collection.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("deck_name", name="uq_anki_deck_collection_deck_name"),
        sa.UniqueConstraint(
            "external_deck_id", name="uq_anki_deck_collection_external_deck"
        ),
        sa.UniqueConstraint(
            "subtitle_collection_id", name="uq_anki_deck_collection_subtitle_collection"
        ),
        comment="字幕集合与 Anki 集合级 deck 的一对一映射。",
    )
    op.create_table(
        "subtitle_file",
        sa.Column("id", sa.Integer(), nullable=False, comment="字幕文件内部自增主键。"),
        sa.Column(
            "collection_id", sa.Integer(), nullable=False, comment="所属字幕集合 ID。"
        ),
        sa.Column(
            "content_hash",
            sa.Text(),
            nullable=False,
            comment="字幕文件内容哈希，用于识别文件变化，不用于去重。",
        ),
        sa.Column("name", sa.Text(), nullable=False, comment="字幕文件名称。"),
        sa.Column(
            "path", sa.Text(), nullable=False, comment="字幕文件的规范化绝对路径。"
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"], ["subtitle_collection.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "collection_id", "name", name="uq_subtitle_file_collection_name"
        ),
        sa.UniqueConstraint("path", name="uq_subtitle_file_path"),
        comment="字幕集合中的本地字幕文件。",
    )
    with op.batch_alter_table("subtitle_file", schema=None) as batch_op:
        batch_op.create_index(
            "subtitle_file_collection", ["collection_id"], unique=False
        )

    op.create_table(
        "anki_deck",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
            comment="Anki 最小 deck 映射内部自增主键。",
        ),
        sa.Column(
            "deck_collection_id",
            sa.Integer(),
            nullable=False,
            comment="所属 Anki 集合级 deck 映射 ID。",
        ),
        sa.Column(
            "subtitle_file_id",
            sa.Integer(),
            nullable=False,
            comment="对应的字幕文件 ID。",
        ),
        sa.Column(
            "external_deck_id",
            sa.BigInteger(),
            nullable=True,
            comment="Anki 返回的远端 deck ID；尚未同步时为空。",
        ),
        sa.Column(
            "deck_name", sa.Text(), nullable=False, comment="Anki deck 完整名称。"
        ),
        sa.Column(
            "last_synced_at",
            sa.DateTime(),
            nullable=True,
            comment="最后一次同步成功时间。",
        ),
        sa.ForeignKeyConstraint(
            ["deck_collection_id"], ["anki_deck_collection.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["subtitle_file_id"], ["subtitle_file.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("deck_name", name="uq_anki_deck_deck_name"),
        sa.UniqueConstraint("external_deck_id", name="uq_anki_deck_external_deck"),
        sa.UniqueConstraint(
            "id", "deck_collection_id", name="uq_anki_deck_id_deck_collection"
        ),
        sa.UniqueConstraint("subtitle_file_id", name="uq_anki_deck_subtitle_file"),
        comment="字幕文件与 Anki 最小 deck 的一对一映射。",
    )
    with op.batch_alter_table("anki_deck", schema=None) as batch_op:
        batch_op.create_index(
            "idx_anki_deck_deck_collection", ["deck_collection_id"], unique=False
        )

    op.create_table(
        "subtitle_entry",
        sa.Column("id", sa.Integer(), nullable=False, comment="字幕条目内部自增主键。"),
        sa.Column(
            "subtitle_file_id",
            sa.Integer(),
            nullable=False,
            comment="所属字幕文件 ID。",
        ),
        sa.Column(
            "number", sa.Integer(), nullable=False, comment="字幕文件中的条目编号。"
        ),
        sa.Column(
            "start_ms",
            sa.Integer(),
            nullable=False,
            comment="字幕开始时间，媒体相对毫秒。",
        ),
        sa.Column(
            "end_ms",
            sa.Integer(),
            nullable=False,
            comment="字幕结束时间，媒体相对毫秒。",
        ),
        sa.Column("text_ja", sa.Text(), nullable=False, comment="字幕中的日文文本。"),
        sa.Column(
            "text_zh_hans",
            sa.Text(),
            nullable=True,
            comment="字幕中的简体中文文本；没有翻译时为空。",
        ),
        sa.CheckConstraint("end_ms >= start_ms", name="ck_subtitle_entry_time_range"),
        sa.CheckConstraint("number >= 0", name="ck_subtitle_entry_number"),
        sa.CheckConstraint("start_ms >= 0", name="ck_subtitle_entry_start_ms"),
        sa.ForeignKeyConstraint(
            ["subtitle_file_id"], ["subtitle_file.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "subtitle_file_id", "number", name="uq_subtitle_entry_file_number"
        ),
        comment="字幕文件中的一条时间轴字幕。",
    )
    with op.batch_alter_table("subtitle_entry", schema=None) as batch_op:
        batch_op.create_index(
            "subtitle_entry_file", ["subtitle_file_id", "number"], unique=False
        )

    op.create_table(
        "anki_note",
        sa.Column(
            "id", sa.Integer(), nullable=False, comment="Anki note 映射内部自增主键。"
        ),
        sa.Column("guid", sa.Text(), nullable=False, comment="Anki note 的稳定 GUID。"),
        sa.Column(
            "external_note_id",
            sa.BigInteger(),
            nullable=True,
            comment="AnkiConnect 返回的远端 note ID；尚未同步时为空。",
        ),
        sa.Column(
            "deck_collection_id",
            sa.Integer(),
            nullable=False,
            comment="所属 Anki 集合级 deck 映射 ID。",
        ),
        sa.Column(
            "deck_id",
            sa.Integer(),
            nullable=False,
            comment="note 当前所在的 Anki 最小 deck 映射 ID。",
        ),
        sa.Column(
            "word_id", sa.Integer(), nullable=False, comment="对应的词典词条 ID。"
        ),
        sa.Column(
            "last_synced_at",
            sa.DateTime(),
            nullable=True,
            comment="最后一次同步成功时间。",
        ),
        sa.ForeignKeyConstraint(
            ["deck_id", "deck_collection_id"],
            ["anki_deck.id", "anki_deck.deck_collection_id"],
            name="fk_anki_note_deck_collection",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["word_id"], ["word.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_note_id", name="uq_anki_note_external_note"),
        sa.UniqueConstraint("guid", name="uq_anki_note_guid"),
        sa.UniqueConstraint(
            "word_id", "deck_collection_id", name="uq_anki_note_word_deck_collection"
        ),
        comment="词典词条在 Anki 集合级 deck 中的稳定 note 映射。",
    )
    with op.batch_alter_table("anki_note", schema=None) as batch_op:
        batch_op.create_index("anki_note_deck", ["deck_id"], unique=False)
        batch_op.create_index("anki_note_word", ["word_id"], unique=False)

    op.create_table(
        "word_occurrence",
        sa.Column("id", sa.Integer(), nullable=False, comment="词项出现内部自增主键。"),
        sa.Column(
            "entry_id", sa.Integer(), nullable=False, comment="所属字幕条目 ID。"
        ),
        sa.Column(
            "word_id", sa.Integer(), nullable=False, comment="匹配到的词典词条 ID。"
        ),
        sa.Column(
            "word_form_id",
            sa.Integer(),
            nullable=False,
            comment="匹配到的词典词形 ID。",
        ),
        sa.Column(
            "matched_text",
            sa.Text(),
            nullable=False,
            comment="在字幕日文文本中命中的实际文本。",
        ),
        sa.Column(
            "position",
            sa.Integer(),
            nullable=False,
            comment="同一个字幕条目内的出现位置标识。",
        ),
        sa.CheckConstraint("position >= 0", name="ck_word_occurrence_position"),
        sa.ForeignKeyConstraint(
            ["entry_id"], ["subtitle_entry.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["word_form_id"], ["word_form.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["word_id"], ["word.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "entry_id",
            "word_id",
            "word_form_id",
            "position",
            name="uq_word_occurrence_entry_word_form_position",
        ),
        comment="字幕条目中已解析到词典词形的词项出现。",
    )
    with op.batch_alter_table("word_occurrence", schema=None) as batch_op:
        batch_op.create_index("word_occurrence_entry", ["entry_id"], unique=False)
        batch_op.create_index("word_occurrence_form", ["word_form_id"], unique=False)
        batch_op.create_index("word_occurrence_word", ["word_id"], unique=False)

    op.create_table(
        "anki_note_occurrence",
        sa.Column(
            "id", sa.Integer(), nullable=False, comment="note 词项关联内部自增主键。"
        ),
        sa.Column(
            "anki_note_id",
            sa.Integer(),
            nullable=False,
            comment="所属 Anki note 映射 ID。",
        ),
        sa.Column(
            "occurrence_id",
            sa.Integer(),
            nullable=False,
            comment="已追加到该 note 的字幕词项出现 ID。",
        ),
        sa.ForeignKeyConstraint(["anki_note_id"], ["anki_note.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["occurrence_id"], ["word_occurrence.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "anki_note_id",
            "occurrence_id",
            name="uq_anki_note_occurrence_note_occurrence",
        ),
        comment="Anki note 已引用的字幕词项出现证据。",
    )
    with op.batch_alter_table("anki_note_occurrence", schema=None) as batch_op:
        batch_op.create_index(
            "anki_note_occurrence_note", ["anki_note_id"], unique=False
        )
        batch_op.create_index(
            "anki_note_occurrence_occurrence", ["occurrence_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("anki_note_occurrence", schema=None) as batch_op:
        batch_op.drop_index("anki_note_occurrence_occurrence")
        batch_op.drop_index("anki_note_occurrence_note")

    op.drop_table("anki_note_occurrence")
    with op.batch_alter_table("word_occurrence", schema=None) as batch_op:
        batch_op.drop_index("word_occurrence_word")
        batch_op.drop_index("word_occurrence_form")
        batch_op.drop_index("word_occurrence_entry")

    op.drop_table("word_occurrence")
    with op.batch_alter_table("anki_note", schema=None) as batch_op:
        batch_op.drop_index("anki_note_word")
        batch_op.drop_index("anki_note_deck")

    op.drop_table("anki_note")
    with op.batch_alter_table("subtitle_entry", schema=None) as batch_op:
        batch_op.drop_index("subtitle_entry_file")

    op.drop_table("subtitle_entry")
    with op.batch_alter_table("anki_deck", schema=None) as batch_op:
        batch_op.drop_index("idx_anki_deck_deck_collection")

    op.drop_table("anki_deck")
    with op.batch_alter_table("subtitle_file", schema=None) as batch_op:
        batch_op.drop_index("subtitle_file_collection")

    op.drop_table("subtitle_file")
    op.drop_table("anki_deck_collection")
    op.drop_table("subtitle_collection")
    # ### end Alembic commands ###
